{
 "title": "App Performance",
 "tags": [
  "Laravel",
  "TraceGuard"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(prometheus_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(laravel_prometheus_http_requests_total{status=~\"5..\"}[1m])) / sum(rate(laravel_prometheus_http_requests_total[1m])) * 100",
     "legendFormat": "Error Rate %"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(laravel_prometheus_http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P95 Latency"
    }
   ]
  },
  {
   "title": "Active Users Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "Active_Users", "legendFormat": "Active Users" }
   ]
  }
 ]
}